# Generated by Django 5.1.6 on 2025-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
