# Generated by Django 5.1.6 on 2025-02-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
